### ISSUE TITLE
if not found ip then not JSONP answer 

### ISSUE THREAD

**Issue by artzub** [nekudo/shiny_geoip#1]
I tried to use your service by jsonp request and if your service not found ip then it answers not jsonp format.

Try this http://geoip.nekudo.com/api/10.0.97.3?callback=d3.jsonp.KHTmQBEaORpDfkA

Can you fix it, please?

Thanks!

**Comment by lemmingzshadow** [comment]
Fixed.

**Comment by artzub** [comment]
Wow!!! Very fast!!! Thanks a lot! :+1:
