### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by sarath49** [nekudo/shiny_geoip#10]
http://geoip.nekudo.com/api/ returns undefined for IPv6, though works smootly for IPv4.

**Comment by nekudo** [comment]
Hello,

seems to work fine in general:
http://geoip.nekudo.com/api/2001:56a:6fe5:8795::b9ff:9101
http://geoip.nekudo.com/api/2a03:2880:2030:cff9:face:b00c:0:8000

If you found an IP that does not work please see this issue:
https://github.com/nekudo/shiny_geoip/issues/7

**Comment by sarath49** [comment]
The issue appear to happen in android chrome browser and not in firefox browser.
I checked today too, In chrome it was showing Australia, while in firefox it showing correct location i.e. India.

http://geoip.nekudo.com/api/

Thanks

**Comment by nekudo** [comment]
It most probably does not depend on the browser but is a problem with the mobile network. If you have an IP from a mobile carrier geolocation will often be very inaccurate.

**Comment by sarath49** [comment]
Hmm.
But this issue does not seem to show up in other geolocation api service like freegeoip.net which uses same maxmind GeoLite2 City db.

**Comment by nekudo** [comment]
Can you please visit the following URL with device which is not working and paste the results here so I have some data for debugging. Thx.

http://geoip.nekudo.com/server_dump.php

**Comment by sarath49** [comment]
Array ( [USER] => nekudo [HOME] => /var/www [HTTP_USER_AGENT] => Mozilla/5.0 (Linux; Android 5.1.1; Lenovo A6020a46 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36 [HTTP_CONNECTION] => Keep-alive [HTTP_X_FORWARDED_FOR] => 2405:204:d005:96aa:1e91:94f4:80d6:9c6a [HTTP_VIA] => 1.1 Chrome-Compression-Proxy [HTTP_UPGRADE_INSECURE_REQUESTS] => 1 [HTTP_SCHEME] => http [HTTP_SAVE_DATA] => on [HTTP_FORWARDED] => for="[2405:204:d005:96aa:1e91:94f4:80d6:9c6a]" [HTTP_DNT] => 1 [HTTP_CACHE_CONTROL] => max-age=0 [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.8,ms;q=0.6 [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 [HTTP_HOST] => geoip.nekudo.com [REDIRECT_STATUS] => 200 [SERVER_NAME] => geoip.nekudo.com [SERVER_PORT] => 80 [SERVER_ADDR] => 95.85.46.50 [REMOTE_PORT] => 60544 [REMOTE_ADDR] => 64.233.173.27 [SERVER_SOFTWARE] => nginx/1.11.10 [GATEWAY_INTERFACE] => CGI/1.1 [REQUEST_SCHEME] => http [SERVER_PROTOCOL] => HTTP/1.1 [DOCUMENT_ROOT] => /var/www/geoip.nekudo.com/www [DOCUMENT_URI] => /server_dump.php [REQUEST_URI] => /server_dump.php [SCRIPT_NAME] => /server_dump.php [CONTENT_LENGTH] => [CONTENT_TYPE] => [REQUEST_METHOD] => GET [QUERY_STRING] => [SCRIPT_FILENAME] => /var/www/geoip.nekudo.com/www/server_dump.php [FCGI_ROLE] => RESPONDER [PHP_SELF] => /server_dump.php [REQUEST_TIME_FLOAT] => 1488000802.7339 [REQUEST_TIME] => 1488000802 )

**Comment by sarath49** [comment]
"city":false,"country":[],"location":{"accuracy_radius":1000,"latitude":35,"longitude":105,"time_zone":"Australia\/Perth"},"ip":"64.233.173.28"}

**Comment by sarath49** [comment]
Array ( [USER] => nekudo [HOME] => /var/www/ [FCGI_ROLE] => RESPONDER [SCRIPT_FILENAME] => /var/www/geoip.nekudo.com/www/server_dump.php [QUERY_STRING] => [REQUEST_METHOD] => GET [CONTENT_TYPE] => [CONTENT_LENGTH] => [SCRIPT_NAME] => /server_dump.php [REQUEST_URI] => /server_dump.php [DOCUMENT_URI] => /server_dump.php [DOCUMENT_ROOT] => /var/www/geoip.nekudo.com/www [SERVER_PROTOCOL] => HTTP/1.1 [REQUEST_SCHEME] => http [GATEWAY_INTERFACE] => CGI/1.1 [SERVER_SOFTWARE] => nginx/1.11.10 [REMOTE_ADDR] => 137.97.4.194 [REMOTE_PORT] => 43562 [SERVER_ADDR] => 178.62.250.181 [SERVER_PORT] => 80 [SERVER_NAME] => geoip.nekudo.com [REDIRECT_STATUS] => 200 [HTTP_HOST] => geoip.nekudo.com [HTTP_USER_AGENT] => Mozilla/5.0 (Android 5.1.1; Mobile; rv:50.0) Gecko/50.0 Firefox/50.0 [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 [HTTP_ACCEPT_LANGUAGE] => en-US,en-IN;q=0.7,en;q=0.3 [HTTP_ACCEPT_ENCODING] => gzip, deflate [HTTP_CONNECTION] => keep-alive [HTTP_UPGRADE_INSECURE_REQUESTS] => 1 [PHP_SELF] => /server_dump.php [REQUEST_TIME_FLOAT] => 1488001177.8427 [REQUEST_TIME] => 1488001177 )

**Comment by sarath49** [comment]
Google 'What is my IP' states what is for HTTP_X_FORWARDED_FOR for chrome. both remote address seems to be inaccurate.

**Comment by nekudo** [comment]
I adjusted the code so that it now checks if the HTTP_X_FORWARDED_FOR header is set. Hopefully you'll get a better result now.

**Comment by sarath49** [comment]
Hi, 
This now works cool in chrome . But still in firefox it checks for Remote Address as work around as we see HTTP_X_FORWARDED_FOR is not present (second paste of server_dump.php). While it shows correct location for now (REMOTE_ADDR), but it may not be correct location tomorrow as when different IPv6 arise in this network or other network using IPv6 forwarded from proxy cache.

Can we look for a workaround on this too.

Thank You

**Comment by nekudo** [comment]
Unfortunately in the second example you provided there is only the REMOTE_ADDR field present. So as there is no other IP information I'm afraid there is nothing I can do in this case.

**Comment by sarath49** [comment]
Thank you.

**Comment by wizajay** [comment]
Hi, I am seeing an IPv4 through ur api while all others are showing a IPv6. Do you have any preference set to IPv4?

On http://geoip.nekudo.com/api
`{"city":false,"country":{"name":"India","code":"IN"},"location":{"accuracy_radius":1000,"latitude":20,"longitude":77,"time_zone":"Asia\/Kolkata"},"ip":"157.51.211.219"}`

On http://api.petabyet.com/geoip/
`{"longitude":77,"latitude":20,"asn":"AS55836","offset":"5","ip":"2405:204:710c:da87:10cc:70ec:7c2f:8034","area_code":"0","continent_code":"AS","dma_code":"0","timezone":"Asia\/Kolkata","country_code":"IN","isp":"Reliance Jio Infocomm Limited","country":"India","country_code3":"IND"}
`

And, are these extra info found on petabyet api omitted or is it not available with Maxmind GeoLite2 Database? Thank you.

**Comment by nekudo** [comment]
Hi,

if you want to use a specific IP just provide it in your Request, like:
https://geoip.nekudo.com/api/2405:204:710c:da87:10cc:70ec:7c2f:8034

Otherwise the API uses whatever is provided via $_SERVER['REMOTE_ADDR'].

If you want all available information from the maxmind database, use the "full" argument:
https://geoip.nekudo.com/api/full/2405:204:710c:da87:10cc:70ec:7c2f:8034

I can't tell where petabyet get's is data from as I don't know their API or sourcecode ;)

Regards
Simon

**Comment by wizajay** [comment]
Hi. Thanks for the reply. I had missed that and your code provides more data too than petabyet. But the full data shows like this for me when i click https://geoip.nekudo.com/api/full/2405:204:710c:da87:10cc:70ec:7c2f:8034. I tried on opera & chromium browser. Do you see it correctly with proper encoding?
`{"city":{"geoname_id":1264527,"names":{"de":"Chennai","en":"Chennai","es":"Madr\u00e1s","fr":"Chennai","ja":"\u30c1\u30a7\u30f3\u30ca\u30a4","pt-BR":"Chennai","ru":"\u0427\u0435\u043d\u043d\u0430\u0438","zh-CN":"\u91d1\u5948"}},"continent":{"code":"AS","geoname_id":6255147,"names":{"de":"Asien","en":"Asia","es":"Asia","fr":"Asie","ja":"\u30a2\u30b8\u30a2","pt-BR":"\u00c1sia","ru":"\u0410\u0437\u0438\u044f","zh-CN":"\u4e9a\u6d32"}},"country":{"geoname_id":1269750,"iso_code":"IN","names":{"de":"Indien","en":"India","es":"India","fr":"Inde","ja":"\u30a4\u30f3\u30c9","pt-BR":"\u00cdndia","ru":"\u0418\u043d\u0434\u0438\u044f","zh-CN":"\u5370\u5ea6"}},"location":{"accuracy_radius":200,"latitude":13.0833,"longitude":80.2833,"time_zone":"Asia\/Kolkata"},"postal":{"code":"600015"},"registered_country":{"geoname_id":1269750,"iso_code":"IN","names":{"de":"Indien","en":"India","es":"India","fr":"Inde","ja":"\u30a4\u30f3\u30c9","pt-BR":"\u00cdndia","ru":"\u0418\u043d\u0434\u0438\u044f","zh-CN":"\u5370\u5ea6"}},"subdivisions":[{"geoname_id":1255053,"iso_code":"TN","names":{"en":"Tamil Nadu","fr":"Tamil Nadu","ja":"\u30bf\u30df\u30eb\u30fb\u30ca\u30fc\u30c9\u30a5\u5dde","ru":"\u0422\u0430\u043c\u0438\u043b\u043d\u0430\u0434","zh-CN":"\u6cf0\u7c73\u5c14\u7eb3\u5fb7\u90a6"}}],"traits":{"ip_address":"157.50.14.117"}}`

**Comment by nekudo** [comment]
That's because the data is a json encoded string. Your application needs to decode the json data. Than everything is utf-8 encoded. Of course if you want to display all the different languages you'll need fonts for that. 
Btw: Chrome can decode json data on the fly in its developer tools:

![image](https://user-images.githubusercontent.com/1132928/40885994-97326ed2-6730-11e8-9ded-74928deb93b2.png)
