### ISSUE TITLE
Timezone as "hour" offset from GMT/UTC

### ISSUE THREAD

**Issue by sl1331** [nekudo/shiny_geoip#11]
This is a tremendous GEO lookup. Thank you. Wondering if it is easy to add a property to the location object that represents the timezone as hour offset from GMT/UTC (+/-). Doesn't have to identify daylight savings changes. The timezone string is helpful but requires significant parsing/mapping depending on the underlying system being used to determine the timezone hour offset. Note that this application is for a server-side request where the timezone offset in Date objects represents the "server's" location so we need to use the timezone from the lookup results to get an accurate idea of what timezone the user is in. Thank you so much.

**Comment by nekudo** [comment]
Unfortunately this information is not included in the MaxMind Database, so to provide this information I would need to add it to the result after the actual lookup.This has two disadvantages:

1. There would be a second (timezone-offset database) that has to be maintained.
2. Adding information from a second database to the result would have a negative impact on performance. (which absolutely matters when doing lots of requests per second.)

This is why I will not add this additional information to the results.

**Comment by sl1331** [comment]
Understood. Thanks.
