### ISSUE TITLE
Return data in better format for type full

### ISSUE THREAD

**Issue by savinash47** [nekudo/shiny_geoip#12]
You have been doing a great job with this api.

But this could be a great improvement.

For e.g. if i call the endpoint 'http://geoip.nekudo.com/api/en/full' it doesn't return the ip address and doesn't format data very well. State is inside subdivisions and doesn't respect the language constraint for en. 

It could be a a great improvement and will increase the crowd using this endpioint

**Comment by nekudo** [comment]
`{
    "continent": {
        "code": "EU",
        "geoname_id": 6255148,
        "names": {
            "de": "Europa",
            "en": "Europe",
            "es": "Europa",
            "fr": "Europe",
            "ja": "\u30e8\u30fc\u30ed\u30c3\u30d1",
            "pt-BR": "Europa",
            "ru": "\u0415\u0432\u0440\u043e\u043f\u0430",
            "zh-CN": "\u6b27\u6d32"
        }
    },
    "country": {
        "geoname_id": 2921044,
        "iso_code": "DE",
        "names": {
            "de": "Deutschland",
            "en": "Germany",
            "es": "Alemania",
            "fr": "Allemagne",
            "ja": "\u30c9\u30a4\u30c4\u9023\u90a6\u5171\u548c\u56fd",
            "pt-BR": "Alemanha",
            "ru": "\u0413\u0435\u0440\u043c\u0430\u043d\u0438\u044f",
            "zh-CN": "\u5fb7\u56fd"
        }
    },
    "location": {
        "accuracy_radius": 10,
        "latitude": 51.45,
        "longitude": 7.0167,
        "time_zone": "Europe/Berlin"
    },
    "registered_country": {
        "geoname_id": 2921044,
        "iso_code": "DE",
        "names": {
            "de": "Deutschland",
            "en": "Germany",
            "es": "Alemania",
            "fr": "Allemagne",
            "ja": "\u30c9\u30a4\u30c4\u9023\u90a6\u5171\u548c\u56fd",
            "pt-BR": "Alemanha",
            "ru": "\u0413\u0435\u0440\u043c\u0430\u043d\u0438\u044f",
            "zh-CN": "\u5fb7\u56fd"
        }
    },
    "subdivisions": [
        {
            "geoname_id": 2861876,
            "iso_code": "NW",
            "names": {
                "de": "Nordrhein-Westfalen",
                "en": "North Rhine-Westphalia",
                "es": "Renania del Norte-Westfalia",
                "fr": "Rh\u00e9nanie du Nord-Westphalie",
                "ru": "\u0421\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u0420\u0435\u0439\u043d-\u0412\u0435\u0441\u0442\u0444\u0430\u043b\u0438\u044f"
            }
        }
    ],
    "traits": {
        "ip_address": "89.1.31.144"
    }
}`

The IP address is included in traits->ip_address.
Using the flags "full" and and a language key together has no effect as "full" includes all available languages. The data-structure itself is provided by the maxmind database and not changed in this API.
