### ISSUE TITLE
Unable to get instance working. Returns dispatch(); 

### ISSUE THREAD

**Issue by Spotlightsrule** [nekudo/shiny_geoip#13]
Hello. i recently tried to set up my own instance of this api on my own server running Ubuntu 14.04. On the server, the api was installed successfully and the requests were modified to be sent to example.com/www which is where the index.php file is in the code. The database was also downloaded via the sh file in cli. The api returned dispatch(); upon calling the index.php file, however, and it may be due to a code error. Please fix this issue.

**Comment by nekudo** [comment]
Hello,

please paste the exact/complete php-error message so I have a chance to debug this. "dispatch();" is just a method name which you should not see in plain text.

**Comment by Spotlightsrule** [comment]
I solved that initial error because apparently the install didn't have PHP enabled properly. but now it shows no record for my ip and it doesn't respond properly when I try to query an IP. it gives a 404 error instead. The syntax I used was example.com/api/<my ip>

Additionally, I plan to incorporate this api on another server, but in a directory other than the root directory (in /var/www/html/geoip). Is this possible?

**Comment by nekudo** [comment]
The "record not found" most probably results from the fact that you are testing with a local IP.

If "/api" returns a 404 error you have to adjust your url-rewriting. All requests need to be rewritten to the index.php file.

Running this code (without adjustments) in a subfolder will not work. You have to use a domain or subdomain pointing to the projects root folder.

**Comment by Spotlightsrule** [comment]
Thanks so much for the help. It is working fine now.
