### ISSUE TITLE
Add Ability For Multiple Database Integration

### ISSUE THREAD

**Issue by JoeyWebMaster** [nekudo/shiny_geoip#14]
Hello. I recently deployed this project to my server and I wanted to add the ability to support both the city and ASN databases to allow for ISP and ASN queries. I tested by swapping out the database location in src/Domain/LocationDomain.php for the ASN database and the ASN database successfully allowed it to display ASN/ISP queries. However, I wanted to find a way to allow both the city records and asn records to be processed. Is there any way I could go about doing this without completely modifying the project past its original form? Thanks.

**Comment by nekudo** [comment]
Hello,

i'm afraid there is now way to achieve this without modifying the project. You could merge the data from both sources into one output or add additional API endpoints to request data from the ASN database. Either way would result in more or less complex changes to the source code.

Of course you're free to fork the project and adjust it to your requirements.

**Comment by JoeyWebMaster** [comment]
Ok. Does maxmind themselves provide some documentation to achieve this? I noticed that trying to add both makes the api favor one database over the other.

**Comment by Spotrealms** [comment]
See PR #17
