### ISSUE TITLE
The country attribute is always expected to be an object. But for ip address with empty / no country details it's returning empty list causing parsing exception to us.  

### ISSUE THREAD

**Issue by PriyaRKadam** [nekudo/shiny_geoip#15]
The country attribute is always expected to be an object. But for ip address with empty / no country details it's returning empty list causing parsing exception to us.  

Eg, http://geoip.nekudo.com/api/107.167.97.196
Output : {"city":false,"country":[],"location":{"accuracy_radius":1000,"latitude":35,"longitude":105,"time_zone":"Australia\/Perth"},"ip":"107.167.97.196"}

Why don't you directly send empty object rather than empty list.

**Comment by PriyaRKadam** [comment]
@nekudo  : Hey friend. .hopping to get some response from you soon.

**Comment by nekudo** [comment]
Fixed. API will now return an empty object instead of an empty array.
