### ISSUE TITLE
Need to reduce response time for requests. 

### ISSUE THREAD

**Issue by PriyaRKadam** [nekudo/shiny_geoip#16]
Hi Team,

Currently we are observing response time for geoip.nekudo.com/api/xx as  245ms to 556ms, which is somewhat high. 
Can you please help us improve this response time. 
![ipresolutionrequestlatency](https://user-images.githubusercontent.com/32698491/32212168-c1e03c52-be3b-11e7-9435-ad48e034feb6.PNG)

Regards,
Priya

**Comment by nekudo** [comment]
Hello. I'm afraid there is noting I can do about that. I checked the server graphs and it seems all normal. The hoster also does doesn't report any incidents. Response times from Germany are about 50-60ms which is the regular speed.

The API servers are however located in the Netherlands so depending on your locations response time may be slower. In any case: If you need fast response times you can always setup your on API on an server near you - or even faster: Use the maxmind database directly on your websever without querying any API.

Regards
Simon
