### ISSUE TITLE
Abuse Question

### ISSUE THREAD

**Issue by oscar0812** [nekudo/shiny_geoip#18]
What is considered an abuse of this api? I'm aware that there is no limits by default, but what type of abuse would get my ip blocked?

**Comment by nekudo** [comment]
An IP may get block for unreasonable usage of the API like e.g. automatically scanning the whole IPv4 address range even thought the database is available for free. 
Also usage of the API in any kind of malware e.g. can result in your IP being blocked.

Hope this will answer your question.
