### ISSUE TITLE
Migration to PHP 7

### ISSUE THREAD

**Issue by teamcoltra** [nekudo/shiny_geoip#19]
Your migration to PHP7 is not backwards compatible with previous versions of PHP for instance line 80 gives a fatal error now. Perhaps there should be two different branches?

**Comment by teamcoltra** [comment]
I see this is actually already addressed in the releases but I would still suggest a separate branch so any bugs or security flaws can be addressed independently.

**Comment by nekudo** [comment]
Hello,

as you can see here https://secure.php.net/supported-versions.php PHP 5.6 (and even 7.0) are already in the "security fixes only" phase and will soon reach there end life with no updates at all. This is why I won't provide an actively maintained version for PHP 5.6 any longer. 

In case of a security related bug I will of course provide a fix for the PHP 5.6 version until the end of this year. Other than that there won't be any updates. Hope this answers your question.
