### ISSUE TITLE
Uptime

### ISSUE THREAD

**Issue by josephmiller2000** [nekudo/shiny_geoip#21]
Just want to make sure, do you guys keep the server? 24*7 and the service running? Am gonna use this in one of my production site. So dont want to see the API going down randomly.

Let me know if you guys offer any paid service too. ( A small amount )

**Comment by nekudo** [comment]
Hello. Of course I try to keep the API online without any downtimes. But: This is a free private project without any guarantees. Use it as you like, but there is no premium-service or uptime guarantee.
