### ISSUE TITLE
The coordinate system used for the latitude and longitude

### ISSUE THREAD

**Issue by stulzq** [nekudo/shiny_geoip#24]
I would like to ask if the latitude and longitude through ip query is not the same as the WGS84 coordinate system, which is the same as that used by Google Maps.

**Comment by nekudo** [comment]
Hi,

as this information can not be found in the MaxMind Database Documentation (https://dev.maxmind.com/geoip/geoip2/geoip2-city-country-csv-databases/) I can't tell. But you can definitely use the coordinates to display locations on a google map. For further questions regarding the database please contact MaxMind directly as this API simply uses this database.
