### ISSUE TITLE
Language param

### ISSUE THREAD

**Issue by ryancwalsh** [nekudo/shiny_geoip#26]
There is probably nothing wrong, and I'm probably just confused when reading the docs.

It seems like https://geoip.nekudo.com/api/87.79.99.25/en/full returns more than English (when all I wanted was English, and I seem to need to specify "full" because I want to see the US state / subdivision):

```
{
  "city": {
    "geoname_id": 2886242,
    "names": {
      "de": "K\\u00f6ln",
      "en": "Cologne",
      "es": "Colonia",
      "fr": "Cologne",
      "ja": "\\u30b1\\u30eb\\u30f3",
      "pt-BR": "Col\\u00f4nia",
      "ru": "\\u041a\\u0451\\u043b\\u044c\\u043d",
      "zh-CN": "\\u79d1\\u9686"
    }
  },
  "continent": {
    "code": "EU",
    "geoname_id": 6255148,
    "names": {
      "de": "Europa",
      "en": "Europe",
      "es": "Europa",
      "fr": "Europe",
      "ja": "\\u30e8\\u30fc\\u30ed\\u30c3\\u30d1",
      "pt-BR": "Europa",
      "ru": "\\u0415\\u0432\\u0440\\u043e\\u043f\\u0430",
      "zh-CN": "\\u6b27\\u6d32"
    }
  },
  "country": {
    "geoname_id": 2921044,
    "is_in_european_union": true,
    "iso_code": "DE",
    "names": {
      "de": "Deutschland",
      "en": "Germany",
      "es": "Alemania",
      "fr": "Allemagne",
      "ja": "\\u30c9\\u30a4\\u30c4\\u9023\\u90a6\\u5171\\u548c\\u56fd",
      "pt-BR": "Alemanha",
      "ru": "\\u0413\\u0435\\u0440\\u043c\\u0430\\u043d\\u0438\\u044f",
      "zh-CN": "\\u5fb7\\u56fd"
    }
  },
  "location": {
    "accuracy_radius": 10,
    "latitude": 50.9387,
    "longitude": 6.9547,
    "time_zone": "Europe\\/Berlin"
  },
  "postal": {
    "code": "50667"
  },
  "registered_country": {
    "geoname_id": 2921044,
    "is_in_european_union": true,
    "iso_code": "DE",
    "names": {
      "de": "Deutschland",
      "en": "Germany",
      "es": "Alemania",
      "fr": "Allemagne",
      "ja": "\\u30c9\\u30a4\\u30c4\\u9023\\u90a6\\u5171\\u548c\\u56fd",
      "pt-BR": "Alemanha",
      "ru": "\\u0413\\u0435\\u0440\\u043c\\u0430\\u043d\\u0438\\u044f",
      "zh-CN": "\\u5fb7\\u56fd"
    }
  },
  "subdivisions": [
    {
      "geoname_id": 2861876,
      "iso_code": "NW",
      "names": {
        "de": "Nordrhein-Westfalen",
        "en": "North Rhine-Westphalia",
        "es": "Renania del Norte-Westfalia",
        "fr": "Rh\\u00e9nanie du Nord-Westphalie",
        "ru": "\\u0421\\u0435\\u0432\\u0435\\u0440\\u043d\\u044b\\u0439 \\u0420\\u0435\\u0439\\u043d-\\u0412\\u0435\\u0441\\u0442\\u0444\\u0430\\u043b\\u0438\\u044f"
      }
    }
  ],
  "traits": {
    "ip_address": "87.79.99.25"
  }
}
```

Maybe I'm misunderstanding the instructions for: `language | optional | Two character language code like en or de.`

What would be really cool would be allowing optional GET params such as like this:

https://geoip.nekudo.com/api/?lang=en&type=full&ip=87.79.99.25

This way, we can omit the IP (so that it can be autodetected) yet still specify the language and type.

https://geoip.nekudo.com/api/?lang=en&type=full

With the current approach (using URL segments), it seems that users are required to specify the IP if they also want to specify the language or type.

https://geoip.nekudo.com/api/{How_to_not_specify_IP_here}/en/full

(Or maybe somehow values that don't look like an IP in that segment are ignored?)

**Thanks so much for your amazing service!  I'm very impressed and really appreciate it.**

**Comment by nekudo** [comment]
Hello,

- if you use the "full" parameter all available data is provided. The language parameter makes no sense in this case.
- If you use the language parameter in "short mode" it will return country-, city-names, e.g. in the selected language. (e.g. "en" will return `"city":"Cologne"` vs. "de" which will return `"city":"Köln"`)
- You can always omit the IP. /api/de or /api/full will work fine without the IP parameter.

**Comment by ryancwalsh** [comment]
Thanks, @nekudo .
