### ISSUE TITLE
zipcode support ?

### ISSUE THREAD

**Issue by ouatataz** [nekudo/shiny_geoip#4]
Dear Simon,
I discovered your GeoIP REST API https://geoip.nekudo.com/ tonight and started using it in my project. Thank you very much for providing it for free as well for HTTPS !

Would it be possible to get also zipcodes from JSONP responses ?
Thanks in advance.
All the best

**Comment by lemmingzshadow** [comment]
Hello,

if a zip code is availabe it is already included in the full response. E.g:
http://geoip.nekudo.com/api/84.44.158.117/full 
The zip can be found in postal.code.

Unfortunately the database has not a great coverage of zip-codes. You should also have a look at the GeoName zip-code database: http://download.geonames.org/export/zip/

Btw. there are geoname-ids included in the responses of this API.

**Comment by ouatataz** [comment]
Thank you Simon for your answer.
My problem is that I use your API without providing any IP and I cannot have access to the full response in that way, right ?

**Comment by lemmingzshadow** [comment]
I see. I'll check if I can add a route "/api/full" for full response without an IP this evening and let you know...

**Comment by ouatataz** [comment]
Thank you Simon for your help

**Comment by lemmingzshadow** [comment]
I just updated the application and you can now request full data without providing an IP address:
http://geoip.nekudo.com/api/full

**Comment by ouatataz** [comment]
Thank you very much Simon. It works like a charm. :) Have a nice evening.

**Comment by ouatataz** [comment]
Dear Simon, did you recently removed the postal codes from your full api ? Would it be possible to add them again ? Thank you very much for your help. All the best. FX

**Comment by nekudo** [comment]
Hello.
No, ZIP codes are (if available) still included. See e.g. http://geoip.nekudo.com/api/84.44.158.117/full

**Comment by ouatataz** [comment]
Thank you Simon : here are the results for my IP : http://geoip.nekudo.com/api/194.167.140.1/full
Missing the "city', "postal" and "subdivisions" information. Can you please explain me why ? Is it relying on the MaxMind DB ? THX.

**Comment by nekudo** [comment]
Yes the data is from the maxmind city database. If data is missing I can't do anything about it. I regularly update the database but have no influence on the data included.

**Comment by ouatataz** [comment]
ok it's good to know that you regularly update the db ; that makes sense and explains why these info are now missing ;) thank you very much for support
