### ISSUE TITLE
Cannot get Subdivision values

### ISSUE THREAD

**Issue by saurabh-sharma** [nekudo/shiny_geoip#5]
Trying to use:

`public function getStateName(City $record, $language)
    {
        if (empty($record->subdivisions->names)) {
            return false;
        }
        $stateData = [
            'name' => $this->getLangValue($record->subdivisions->names, $language),
            'code' => $record->subdivisions->isoCode,
        ];
        return $stateData;
    }`
to get subdivision data. but it fails, and returns `false` always.

Also, if you browse in full mode you'll see subdivision as: `"subdivisions":[{"geoname_id":2861876,"iso_code":"NW","names":{"de":"Nordrhein-Westfalen","en":"North Rhine-Westphalia","es":"Renania del Norte-Westfalia","fr":"Rh\u00e9nanie du Nord-Westphalie","ru":"\u0421\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u0420\u0435\u0439\u043d-\u0412\u0435\u0441\u0442\u0444\u0430\u043b\u0438\u044f"}}]`

There seems to be an array within an array that is causing subdivision to surround with `[]`

**Comment by lemmingzshadow** [comment]
I'm not really sure what your questions is as you already answered yourself ;)
subdivisions is an array so "$record->subdivisions->names" does not exists. It would "$record->subdivisions[0]->names" in your example.

**Comment by saurabh-sharma** [comment]
Exactly, but $record->subdivisions[0]->names throws an error page

**Comment by saurabh-sharma** [comment]
Was trying out the same earlier, the issue seemed to be a missing `,` causing the error :stuck_out_tongue_winking_eye:
