### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sky0201** [nekudo/shiny_geoip#6]
how to set json "time_zone":"America\/Los_Angeles" ->  "time_zone":"America/Los_Angeles". no have "\". Sorry im newbie

**Comment by lemmingzshadow** [comment]
It's a default json-encoded string. If you decode it using e.g. "[json_decode](http://php.net/manual/en/function.json-decode.php)" in PHP it will be removed.

**Comment by sky0201** [comment]
thank you so much
