### ISSUE TITLE
Returning Wrong city

### ISSUE THREAD

**Issue by sunnytambi** [nekudo/shiny_geoip#7]
I am using this api from server.
I have tried with one of my mobile's IP (125.18.77.25).
I am located in Mumbai, however the API returns city as New Delhi.
Can you suggest if I am doing something wrong or if the API is buggy?
Here is the full url that I am consuming: http://geoip.nekudo.com/api/125.18.77.25/en/full

**Comment by lemmingzshadow** [comment]
Hello,

the API uses the IP to location database provided by maxmind. See: http://dev.maxmind.com/geoip/geoip2/geolite2/

The database is updated regularly by maxmind but can always contain errors. This project however has no influence on the data within this database.
