### ISSUE TITLE
Can't set the rewrite url on iis 

### ISSUE THREAD

**Issue by thefarmer** [nekudo/shiny_geoip#8]
Hey,
I am not php developer ...:(
I can't setup the site to work for me , I have set the rewrite in the iis like this 
```
<rewrite>
            <rules>
                <rule name="GeoIp">
                    <match url=".*" />
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
```

but when I try to access the url :http://mydomain/api/87.79.99.25
I am getting the message : ":( Page not found."
and url have some loop till the max chars end like this : /index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/index.php/api/87.79.99.25
I have tried to play with the url rewrite with no success :-(

the second thing I want to verify is the DB download file(GeoLite2-Country.mmdb) suppose to be paste to data folder as is or do I need to build it somehow 

Thanks

**Comment by nekudo** [comment]
Hello,

i never used IIS so I can not really answer this but it seems the rules you're looking for are something like this: http://stackoverflow.com/questions/9965124/how-to-rewrite-the-index-php-of-codeigniter-on-windows-azure/9965392#9965392

And: Yes, you can use the mmdb file "as it is" but you should use the City-Database not the Country-Database from Maxmind.
