### ISSUE TITLE
Unable to get location.

### ISSUE THREAD

**Issue by sarath49** [nekudo/shiny_geoip#9]
I am using Shiny GeoIP Tag 1.

followed the steps as provided in readme.
 
Installed and running correctly. Showing default 'Free IP GeoLocation/GeoIp API' homepage with no geoIP information. 

I also tried using grabing information via js ajax callback, still retrieving default homepage instead of JSON data with no location information.

Please Help.

**Comment by nekudo** [comment]
Did you run the software on you local host? In this case you would try to get a location for a local IP which of course can not work.

**Comment by sarath49** [comment]
Ok. Got it
